apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook6
  template:
    metadata:
      labels:
        app: guestbook6
    spec:
      containers:
        - name: guestbook6
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
