apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook2
  template:
    metadata:
      labels:
        app: guestbook2
    spec:
      containers:
        - name: guestbook2
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
