apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook5
  template:
    metadata:
      labels:
        app: guestbook5
    spec:
      containers:
        - name: guestbook5
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
