apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook3
  template:
    metadata:
      labels:
        app: guestbook3
    spec:
      containers:
        - name: guestbook3
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
