apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook4
  template:
    metadata:
      labels:
        app: guestbook4
    spec:
      containers:
        - name: guestbook4
          image: docker.io/library/nginx
          ports:
            - containerPort: 80
